language: php
php:
  - 5.6
  - 7.0
  - nightly

before_script:
  - composer install --no-interaction
  - phpunit install
  
script: php composer.phar selfupdate

script: phpunit --configuration phpunit.xml --coverage-text