language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install --no-interaction

script: php composer.phar selfupdate

script: phpunit --configuration phpunit.xml --coverage-text

deploy:
  provider: pages
  skip_cleanup: false
  on:
    branch: master