language: php

php:
  - 7.0
  - hhvm
  - nightly

before_install:
  - php /home/travis/.phpenv/versions/7.0/bin/composer.phar self-update
before_script:
  - composer install

script: phpunit --configuration phpunit.xml --coverage-text

